theme: minima
title: Radical Project test
description: *To understand is to change, to go beyond oneself* - Sartre
minima:
  date_format: "%b %-d, %Y"
  skin: dark
header_pages:
  - about.md
  - podcast.md